development:
  adapter: mysql2
  database: ShopulseBeta
  pool: 5
  timeout: 5000
  username: root

production:
  adapter: mysql2
  database: ShopulseBeta
  pool: 5
  timeout: 5000
  username: root

test:
  adapter: mysql2
  database: ShopulseBetaTest
  pool: 5
  timeout: 5000
  username: root