development:
  adapter: pg
  database: ShopulseBeta
  pool: 5
  timeout: 5000
  username: root

production:
  adapter: pg
  database: ShopulseBeta
  pool: 5
  timeout: 5000
  username: root

test:
  adapter: pg
  database: ShopulseBetaTest
  pool: 5
  timeout: 5000
  username: root